using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LookAtMouse : MonoBehaviour
{
    void Update()
    {       

             //musen position
             var mouse = Input.mousePosition;

             //positionen av detta objektet relativt till kameran
             var screenPoint = Camera.main.WorldToScreenPoint(transform.localPosition);

             //skillnaden mellan dessa tv책
             var offset = new Vector2(mouse.x - screenPoint.x, mouse.y - screenPoint.y);

             //r채knar ut vinkeln mellan offsetsen och konverterar det fr책n radianer till grader
             var angle = Mathf.Atan2(offset.y, offset.x) * Mathf.Rad2Deg;

             //s채tter rotationen av objektet till vinkeln minus 90 grader
             transform.rotation = Quaternion.Euler(0, 0, angle + 90);
             
    }
}
